### ISSUE TITLE
Use a standard license

### ISSUE THREAD

**Issue by kmturley** [DISTRHO/Kars#2]
License file is here:
https://github.com/DISTRHO/Kars/blob/master/LICENSE

But GitHub detect as custom other license:
https://api.github.com/repos/DISTRHO/Kars/license

This is problematic when using the GitHub API to categorize plugins by license type. Compare to a standard license API request:
https://api.github.com/repos/asb2m10/dexed/license

If you could use a standard license from either:
https://choosealicense.com/

OR the list here:
https://api.github.com/licenses

Would be much appreciated!

**Comment by falkTX** [comment]
GitHub must not be very smart, because this is pretty much a standard MIT/BSD license text.

I guess any text that doesnt fit its exact template will fail.
I can quickly see some examples:
https://github.com/nothings/stb/blob/master/LICENSE
https://api.github.com/repos/nothings/stb/license says "other"

https://github.com/iPlug2/iPlug2/blob/master/LICENSE.txt
https://api.github.com/repos/iPlug2/iPlug2/license says "other"

Somehow https://github.com/lv2/pugl/blob/master/COPYING correctly identifies the license.
The only relevant change in this file compared to kars is "THE SOFTWARE IS PROVIDED" being changed to "THIS SOFTWARE IS PROVIDED".
They mean the same thing.

I am sorry but I am not going to spend my time pleasing github license text detection on a bunch of respositories.
Though I am curious about s/THIS/THE/ if it has any effect.
Wikipedia entry on ISC license has "THE" text too.
If that works, great, otherwise I won't bother.

**Comment by falkTX** [comment]
hmm wait, I am already using "THE" as the wikipedia entry has.
github detects only the "THIS" variant. haha what a joke

**Comment by falkTX** [comment]
did some quick checks. adding a project name to the top of the license file breaks github license detection :facepalm: 

the text was correct all along.
anyway, I will leave it as it is now.

**Comment by kmturley** [comment]
Thanks for investigating. I'm guessing they do a hash of the License file and it has to match exactly (every character)

Understand if you are not going to support.
